
name: Build Projects

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build with JDK 8
    steps:
      - name: Cache Dependencies
        uses: actions/cache@v2.1.5
        with:
          key: maven-dependencies
          path: ~/.m2/repository
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
      - name: Gradle Cache
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: test
      - name: "Clean & Package"
        run: ./gradlew clean test browserProductionWebpack